#!/usr/bin/env ruby

# INSTALL: sudo update-rc.d -f garage_init start 4

`echo "bar" > /tmp/foo`

require 'logger'
require 'fileutils'
require 'tempfile'

# BUNDLE="/usr/local/bin/bundle"
DIR="/home/pi/perfect_pi"
LOG="/root"

logger = Logger.new(File.join(DIR, "log", "startup.log"))

begin
  case ARGV.first
  when /start/
    FileUtils.cd(DIR)
    command = "/usr/local/bin/rackup --daemonize --port 3000"
    logger.info "exec: #{command}"
    exec command
  end
rescue => e
  logger.error %[#{e.class.to_s}\n#{e.backtrace.join("\n")}]
end
