---
private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEowIBAAKCAQEA5CiHmsehABjCsp3hPCe4PQP19SonZqmhgOWcQTAH5zvU0t1V
  E5+kMLtlq06CHFgLKuDsu3Rf+byJKShv9uhW3cBrtmmqkhjj4b40sGxbIBQtShSk
  O8R3fo5GhKXHSnyb4ykeG2MBFAt1ZB01fZGfsNAq56yjXtsmJFh1kENJg9BW5d0Z
  LRn9SM8a8wkptLHSwhPBw2muUa50iEUYIgHeL3gSblWuGkx74i1duf/9J50kUThV
  TAkXEPfFBu48qum1bLSk0LyE8H3vOocp53GxOi3LCz4giGX72VXfDcOIyR0o4CD+
  dS8C1lYMO8GV2etEQiwaFumuNGZDBohdh7OqjQIDAQABAoIBAHoEtujvBEqR82Yl
  CzTppR10hdCUt7eu1oGhylwOfNuMYvhWiE5TXTL2tZvVA75205od6l0iEsXzr4ME
  bkSk4vf7FV/byO4TQ6QR3gnQGTfhsorg2ShhnOpg2pPMOPW8CH6HGePZodT/f8uH
  13iNLdMYsSlvaXusRgzABjed1K4Z9hsbrrPcAcLLGbcklY4oxpN+E4ksp3011vYv
  yvWX+wgd1Ef1aiXqDwlTTuplXikDoJobRyhf2+7F3a2Q4dQh2OFkIbi0Co1jaMF/
  vZ4aqWnMkD1OAowFQpYUnPt6R8wQpwmLwAxlDBIBE7IceP5zQdiYNiCvcLSsf4O/
  tsm1YF0CgYEA96NanKuUvtQW8w1RQ8u3uwMRxVRMB3/w4sb/cnDOTMbRD4/RXIgc
  P0GFFFDeaXaWLzzn9gCJzSdOavkMn8jvqmg7dePCP/V1dLN8kQn3jYmTmZGsbIeO
  1ExzbmuU2gdeVBgdonD+ssXy463IxZWlX9h1/IdTF7MQqwwtmk6LKRsCgYEA69zJ
  oRhnDx6p97fNhxGXpou8XRJ93Pj7mfqpbyogvanT2RHSo6iyseuwgId9+B6ar0xd
  vnoGIlAUnawL790x54Z6bnUmIONaiAiLyl2rKvQ7FFrEH8giFRkIi3fNYhzf+evG
  fYicUmEHx44nPqOPWNVbs1a1Fjkh2a73uRFKnXcCgYAXXeqm7enTN+ASfycz5n0n
  wFpk7FdgPcpVG8Hu4oYU6I3BkiiHOrCvp1cPW7Ig8XeqbWzV4acfHJ5hqa5vRV6Y
  Dc3OifdCYb77jBQs+2vIhzrOOtiyRPhNQAmEWdJp4FgeR0hEk7T02YjZwwQ24LAC
  I0K+2WYVzme8PCHxdYfcEQKBgQCPHzLapkwjSKAqyUXWKD61uSVb9NSbOhqynQAj
  jJTBgkQi/EWtObj1bed0lsNBxJBovxZDdxgxyhY4dyXnL3oQ2/F/BWdVnaBZ25W3
  /o7XScxv1YQdJPxJgR9GQjRGzO68YO3ZTwRMmMR3uzLlN6rMZOt4L61DBvgbd6iq
  jGuSkQKBgCztA3Shf+bgk3DzcJKZj9ITouyqyiPynnDJgkW8te+UpO2m9j++LufN
  9ZSQiW9aB+0Q+9n2e8YS3Pb4fQ6F5B5WYyjlPusKKsygQ5d0zKOamr4mYNbJUBUT
  TSAKNESJopgXLvbr0sjQvnbgYtufLfO48eojl4hEfqo0YxRnh71Z
  -----END RSA PRIVATE KEY-----
public_key: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5CiHmsehABjCsp3hPCe4
  PQP19SonZqmhgOWcQTAH5zvU0t1VE5+kMLtlq06CHFgLKuDsu3Rf+byJKShv9uhW
  3cBrtmmqkhjj4b40sGxbIBQtShSkO8R3fo5GhKXHSnyb4ykeG2MBFAt1ZB01fZGf
  sNAq56yjXtsmJFh1kENJg9BW5d0ZLRn9SM8a8wkptLHSwhPBw2muUa50iEUYIgHe
  L3gSblWuGkx74i1duf/9J50kUThVTAkXEPfFBu48qum1bLSk0LyE8H3vOocp53Gx
  Oi3LCz4giGX72VXfDcOIyR0o4CD+dS8C1lYMO8GV2etEQiwaFumuNGZDBohdh7Oq
  jQIDAQAB
  -----END PUBLIC KEY-----
uri: ws://localhost:3333/cable
device_id: garage a3c4
