---
private_key: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpQIBAAKCAQEAmrxWX0XdFSohBcYZqMJhBoza9VmVdjlOp2TNF2/Ley/NLgny
  vT4JJzXArbB2V2arrjs3uFxo8Bni5tWFyVe8nWkN82KYmpUQIuoTJtYKWbQGnpil
  qsFu4rCFFh9sewUa26LzYsnwVzTjQ35wgboJL2wTLPh5X2BPn+BkHYR6Jre6o7Ts
  VzEQuGFh8VDelCElue6Gli16r3q2RgqyNn6I5Tu9gpRiCVEI+yJUT2uCJPIjW9YG
  CXIL4aooWhYGON2+tYgru1iBqdA51AK3irFvwY5WwmcGz/2IFoF1AlQuGhYumPnI
  RvwIDE8amIc5Z2ZL+EPJ/fjtU8WubzvbIQ8knQIDAQABAoIBAGvhe2aZUvZ6lONt
  pl4eh38FnXMJrkbq1Yeno8X/T6LnROogTXjbU45ez6NJMHjnQDMNXl/PLeqYYbYG
  kGw8G2iz4eIaj8LWwpVVFV0yRa0c8rCIRJi0nBa4c1FlP0DV4k/XYFEz8bkbSoe4
  E8Ceb+D8PLJR2m1AvML+s05RGsj6oiM2lEYhaBTY8LBjSpVJq3vwGVK9478Y19+l
  EHG4SX3cvUCI6Kq4mLJSEUxlZB4AlAGA6p0JMUs6k4tENkgUQrn/YfCXOb4OdBMW
  kyHIueS8HbupA2ddC3KtKXSScdvYpGR203xMbLzZN1mRU2TY3UFmDHHQWFJIGzvA
  pclfWpECgYEAzQmtFteZqygFqm6PnfTXs69hv9hE1HYY4vJCBUqC/WrnZoN3kX/2
  edLdiOiJ+7cjOxXICxunGWYKgxQuMlxi9LgQEwjS3TiqNdBqksh6Q5WpLXb5efGQ
  IZiAHJcUxSJm1GXLOScfLFWy2YgN3yiui2If7JmuHNwvQ7cxt2AIghsCgYEAwTH+
  vO6bD0qnkbfvphh71+PNws3TMChp6+6GrL/UN9QHI5+hQaWEZ1bSuZ3AEA7N7rGk
  8ITu4Zro9Wd6f5gzpBpeDioT6o7/rlnRE8qkj+RTaMN9gxh4GNcEndxVcuH6KJ7q
  YqTITTevtKquCQP/7RT3qP7sVx6i3m1jtR9TH6cCgYEAjGq+AVCxyodkKe4BqPlO
  552KYenoaWBfdrzV/e2je43E323Vau2pjJCeau5l4N7w37vw/bp4W2qIdHBTmuWu
  V03epEp8rkfqOWR8N/3XzYUnER3TiHGodXmM8wd8j+0ZYwg7fu6N6Lzf+R218khY
  ENioaE5u8RDRxZwmDiFUclUCgYEAvWeBYcLfnBdJv0/AEGuyho6cvF5DrNQCPD8G
  I7iRmwYw1Zj7ZDucWh/Byh5BHL0W4euhU/hPpjjUKTuA2jTidAExsttH2U7Gli0S
  EEA8I6HqsCvwEiVcIKY0rXtE/rNTKJ3cFkeM5D8y8IHgy4/zSYCj6Te7hxHPBRfj
  h7+lI8MCgYEAtialch+9+jzjb8X84a8ApH24IbD6lBMIXur2l1OmzDYS6UqEzldL
  E298u1daO6Rr85wPssuxoLBsZn3SDNCwxVaK0P4K1d/HZdyMnxdCbiIqsRP7H3GS
  Tvrv7/uq7yt3f8dBWVZZ5U+dKjNfTLZsjMJWxvkWnswmzr9aXeMMhrs=
  -----END RSA PRIVATE KEY-----
public_key: |
  -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmrxWX0XdFSohBcYZqMJh
  Boza9VmVdjlOp2TNF2/Ley/NLgnyvT4JJzXArbB2V2arrjs3uFxo8Bni5tWFyVe8
  nWkN82KYmpUQIuoTJtYKWbQGnpilqsFu4rCFFh9sewUa26LzYsnwVzTjQ35wgboJ
  L2wTLPh5X2BPn+BkHYR6Jre6o7TsVzEQuGFh8VDelCElue6Gli16r3q2RgqyNn6I
  5Tu9gpRiCVEI+yJUT2uCJPIjW9YGCXIL4aooWhYGON2+tYgru1iBqdA51AK3irFv
  wY5WwmcGz/2IFoF1AlQuGhYumPnIRvwIDE8amIc5Z2ZL+EPJ/fjtU8WubzvbIQ8k
  nQIDAQAB
  -----END PUBLIC KEY-----
server_uri: ws://localhost:3333/cable
device_id: garage 38f5
